all:
  children:
    SIT14:
      children:
        App_Servers:
          hosts:
            app_server_01:
              ansible_ssh_host: sit14vsbl01.dhsie.hawaii.gov
              ansible_connection: ssh
        Web_Servers:
          hosts:
            web_server_01:
              ansible_ssh_host: sit14vsai01.dhsie.hawaii.gov
              ansible_connection: ssh