pipeline {
    agent {
	 node{
	label 'built-in'
	customWorkspace '/tmp/siebel_export'
	 }
	}
      environment {
       def schema_trackingid = ""
	   def status = ""
	   def schema_changed = ""
	   def repository_trackingid = ""
	   def seed_trackingid=""
	   def watermark= "${env.Target_Watermark};SrcEndVer=${env.workspace_num}"
	   def migrationid="${env.migrationid}"
	   def Repository_Name="${env.Repository_Name}"
    }
    stages {
		stage('Cleanup') {
            steps {
                cleanWs()  // Deletes workspace contents
            }
        }
		stage('Environment Name') {
		  steps {
			//echo "Variables: ${env.Environment},${migrationid},${env.Repository_Name},watermark:${watermark}"
			echo "Env_Variable: ${env.Environment}"
			echo "MigrationId_Variable: ${migrationid}"
			echo "RepoName_Variable: ${env.Repository_Name}"
			echo "WaterMark_Variable:${watermark}"
			}
		}
		stage('Checking Schema Changed') {
            steps {
				echo "Checking Schema Changed"
                withCredentials([usernamePassword(credentialsId: "${env.Environment}_SADMIN", usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    script {
                        def apiUrl = "https://${Host_Name}:4430/siebel/v1.0/service/Migration%20Schema%20Service/IsSchemaChanged"
                        def jsonBody = """
						{
							 "body":
							 { 
							 "watermark": "$watermark"
							}
							}
						"""

                        def response = sh(
                            script: """
                                curl -s -X POST '${apiUrl}' \\
                                     -u "$USER:$PASS" \\
                                     -H 'Content-Type: application/json' \\
                                     -d '${jsonBody}'
                            """,
                            returnStdout: true
                        ).trim()
                       	def json = readJSON text: response
                       	schema_changed=json.isschemachanged
                        echo "Schema Changed:${schema_changed}"
                        
                        
                    }
                }
            }
        }
        stage('Schema Export') {
            steps {
			   script {
			   if (schema_changed == "Y"){
                withCredentials([usernamePassword(credentialsId: "${env.Environment}_SADMIN", usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    
                        def apiUrl = "https://${Host_Name}:4430/siebel/v1.0/service/Migration%20Schema%20Service/Export"
                        def jsonBody = """
						{
							 "body":
							 { 
							 "migrationid": "$migrationid"
							}
							}
						"""

                        def response = sh(
                            script: """
                                curl -s -X POST '${apiUrl}' \\
                                     -u "$USER:$PASS" \\
                                     -H 'Content-Type: application/json' \\
                                     -d '${jsonBody}'
                            """,
                            returnStdout: true
                        ).trim()
                       	def json = readJSON text: response
                       	schema_trackingid=json.trackingid
                       	status=json.status
                        echo "Schema Export Response tracking Id:${schema_trackingid}, Status:${status}"
                        
                        
                    }
                }
			  else {
			    echo "No schema change detected, skipping Schema Export"
               }			  
			  }	
            }
        }
         stage('Schema Export Status') {
            steps {
			   script {
			     if (schema_changed == "Y"){
					withCredentials([usernamePassword(credentialsId: "${env.Environment}_SADMIN", usernameVariable: 'USER', passwordVariable: 'PASS')]) { 
							while(true){
									def apiUrl = "https://${Host_Name}:4430/siebel/v1.0/service/Migration%20Schema%20Service/GetStatus"
									def jsonBody = """
									{
										 "body":
										 { 
										 "migrationid": "$migrationid",
										 "trackingid": "$schema_trackingid",
										 "getlog": "true"
										}
										}
									"""

									def response = sh(
										script: """
											curl -s -X POST '${apiUrl}' \\
												 -u "$USER:$PASS" \\
												 -H 'Content-Type: application/json' \\
												 -d '${jsonBody}'
										""",
										returnStdout: true
									).trim()
									def json = readJSON text: response
									status=json.status
									echo "Schema Export Response:$json"
									
									sleep time: 120, unit: 'SECONDS'
									
									if(status!="running")
									{
										echo"Export completed with status:${status} and Schema Tracking Id:$schema_trackingid "
										break
									}
						      }	
							}
					  }		
                }
            }
        }
		stage('Repository Export') {
            steps {
                withCredentials([usernamePassword(credentialsId: "${env.Environment}_SADMIN", usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    script {
                        def apiUrl = "https://${Host_Name}:4430/siebel/v1.0/service/Migration%20Incremental%20Runtime%20Repository%20Data%20Service/Export"
                        def jsonBody = """
						{
							 "body":
							 { 
							  "watermark":"${watermark}", 
							  "migrationid":"$migrationid",
							}
							}
						"""

                        def response = sh(
                            script: """
                                curl -s -X POST '${apiUrl}' \\
                                     -u "$USER:$PASS" \\
                                     -H 'Content-Type: application/json' \\
                                     -d '${jsonBody}'
                            """,
                            returnStdout: true
                        ).trim()
                       	def json = readJSON text: response
						repository_trackingid=json.trackingid
						status=json.status
						echo "Repository Export Tracking Id:$repository_trackingid, Status:$status"
                    }
                }
            }
        }
		stage('Repsitory Export Status') {
            steps {
                withCredentials([usernamePassword(credentialsId: "${env.Environment}_SADMIN", usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    script {
						while(true){
								def apiUrl = "https://${Host_Name}:4430/siebel/v1.0/service/Migration%20Incremental%20Runtime%20Repository%20Data%20Service/GetStatus"
								def jsonBody = """
								{
									 "body":
									 { 
									 "migrationid": "$migrationid",
									 "trackingid": "$repository_trackingid",
									 "getlog": "true"
									}
									}
								"""

								def response = sh(
									script: """
										curl -s -X POST '${apiUrl}' \\
											 -u "$USER:$PASS" \\
											 -H 'Content-Type: application/json' \\
											 -d '${jsonBody}'
									""",
									returnStdout: true
								).trim()
								def json = readJSON text: response
								status=json.status
								echo "$json"
								
							    if(status!="running")
								{
									echo"Export completed with status:${status}"
									echo "Repository Tracking Id:$repository_trackingid"
									break
								}
								sleep time: 120, unit: 'SECONDS'
					  }	   
                    }
                }
            }
        }
		stage('Incremental Seed Export') {
            steps {
                withCredentials([usernamePassword(credentialsId: "${env.Environment}_SADMIN", usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    script {
                        def apiUrl = "https://${Host_Name}:4430/siebel/v1.0/service/Migration%20Incremental%20Application%20Workspace%20Data%20Service/Export"
                        def jsonBody = """
						{
							 "body":
							 { 
							  "watermark":"${env.Target_Watermark}", 
							  "migrationid":"$migrationid",
							}
							}
						"""

                        def response = sh(
                            script: """
                                curl -s -X POST '${apiUrl}' \\
                                     -u "$USER:$PASS" \\
                                     -H 'Content-Type: application/json' \\
                                     -d '${jsonBody}'
                            """,
                            returnStdout: true
                        ).trim()
                       	def json = readJSON text: response
						seed_trackingid=json.trackingid
						status=json.status
						echo "Repository Export Tracking Id:$seed_trackingid, Status:$status"
                    }
                }
            }
        }
		stage('Seed Export Status') {
            steps {
                withCredentials([usernamePassword(credentialsId: "${env.Environment}_SADMIN", usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    script {
						while(true){
								def apiUrl = "https://${Host_Name}:4430/siebel/v1.0/service/Migration%20Incremental%20Application%20Workspace%20Data%20Service/GetStatus"
								def jsonBody = """
								{
									 "body":
									 { 
									 "migrationid": "$migrationid",
									 "trackingid": "$seed_trackingid",
									 "getlog": "true"
									}
									}
								"""

								def response = sh(
									script: """
										curl -s -X POST '${apiUrl}' \\
											 -u "$USER:$PASS" \\
											 -H 'Content-Type: application/json' \\
											 -d '${jsonBody}'
									""",
									returnStdout: true
								).trim()
								def json = readJSON text: response
								status=json.status
								echo "$json"
								
							    if(status!="running")
								{
									echo"Export completed with status:${status}"
									echo "Seed Tracking Id:$seed_trackingid"
									break
								}
								sleep time: 120, unit: 'SECONDS'
					   }	   
                    }
                }
            }
        }
    }
}