all:
  hosts:
    tsai:
      ansible_host: tslim8
      ansible_python_interpreter: /usr/bin/python3
      ansible_connection: ssh  

    PSD11:
      ansible_host: psd11vsbl01.dhsie.hawaii.gov
      ansible_connection: ssh  

