all:
  hosts:
    tses:
      ansible_host: tses
      ansible_port: 2222
      ansible_python_interpreter: /usr/bin/python3
      ansible_connection: ssh  

    tsai:
      ansible_host: tses
      ansible_port: 2222
      ansible_python_interpreter: /usr/bin/python3
      ansible_connection: ssh  

