all:
  hosts:
    nonprod:
      ansible_host: oracle19c
      ansible_connection: ssh
      app_url: "http://localhost:8080"

    prod:
      ansible_host: ses01
      ansible_connection: ssh
      app_url: "https://bses01"

