pipeline {
    agent {
	    node{
			label 'built-in'
			customWorkspace '/var/jenkins_home/workspace/Siebel_Migration_Watermark_Generation'
	    }
	}
        environment {
            def error_message = ""
            def watermark = ""
            def Branch_Name = "master"
            def tmpname="test"
        }
    stages {
		stage('Checkout devops automation repository') {
			steps{			
				checkout scm			
			}
	    }

		stage('Environment Name') {
		  steps {
			echo "Variables: ${env.Environment}"
			}
		}
		stage('Target Environment Watermark') {
            steps {
                withCredentials([usernamePassword(credentialsId: "${env.Environment}_SADMIN", usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    script {
                        def apiUrl = "https://${Host_Name}:4430/siebel/v1.0/migration/connection/${tmpname}/watermark"

                        def jsonBody = """
						    {
							    "fileName": "${env.File_Name}"
							}
						"""

                        def response = sh(
                            script: """
                                curl -s --location --insecure --request POST '${apiUrl}' \\
                                     -u "$USER:$PASS" \\
                                     -H 'Content-Type: application/json' \\
                                     -d '${jsonBody}'
                            """,
                            returnStdout: true
                        ).trim()
						try {
							if (response) {
								echo "Migration API Response: ${response}"
								def json = readJSON text: response
								error_message=json.error
								watermark=json.watermarkFile
								History_ID=json.id
									echo "Schema Export Response ${History_ID}: err:${error_message},  Watermark:${watermark}"
							} else {
								echo "No response received from migration API."
								error "No response received from migration API."
							}
						} catch (Exception e) {
							echo "Failed to parse migration response: ${e.message}"
							error "Failed to parse migration response: ${e.message}"
						}	            
                    }
                }
            }
        }
        stage('Git push') {
            steps{
                withCredentials([string(credentialsId: 'github_access_token_secret', variable: 'GITHUB_TOKEN')]) { 
                    ansiColor('xterm') {
                        ansiblePlaybook(
                            playbook: "${WORKSPACE}/Siebel_Watermark_Generation/ansible_scripts/file_copy.yml",
                            inventory: "${WORKSPACE}/Siebel_Watermark_Generation/ansible_scripts/Inventory/siebel_env.yml",
                            //credentialsId: 'jenkins_private_key',
                            colorized: true,
                            extraVars: [
                                env: "${env.Environment}",
                                repo_name: "bpm",
                                packageFile: "${watermark}",
                                git_token: "${GITHUB_TOKEN}",
                                Branch_Name: "${Branch_Name}"
                            ]
                        )
                    }
                }
            }	
        }
		stage('Send Email'){
		    steps {
			withCredentials([usernamePassword(credentialsId: 'jenkins-username-password', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {

            // Send the email
            emailext(
                to: "cheolmin@gmail.com",
                subject: "${env.Environment} - Siebel Watermark",
                body: """
                <p>Hi Team,</p>
                <p>${env.Environment} Siebel Watermark Generated Successfully.</p>
                <p>Watermark: ${watermark}</p>
                <p>Regards,<br/>DevOps Automation</p>
				""",
                mimeType: 'text/html'
            )
          }
		 } 
	  }	
    }
}