pipeline {
    agent {
	 node{
	label 'built-in'
	customWorkspace '/stage/asi/automations/siebel_import'
	 }
	}
      environment {
       def schema_trackingid = ""
	   def status = ""
	   def repository_trackingid = ""
	   def seed_trackingid=""
	   def migrationid="${env.migrationid}"
	   def Repository_Name="${env.Repository_Name}"
    }
    stages {
		stage('Cleanup') {
            steps {
                cleanWs()  // Deletes workspace contents
            }
        }
		stage('Environment Name') {
		  steps {
			echo "Variables: ${env.Environment},${migrationid},${env.Version},${env.Repository_Name}"
			}
		}
		stage('Repository Import') {
            steps {
			    script{
					 if(repository_id){
							withCredentials([usernamePassword(credentialsId: "${env.Environment}_SADMIN", usernameVariable: 'USER', passwordVariable: 'PASS')]) {
									def apiUrl = "https://${Host_Name}:9112/siebel/v1.0/service/Migration%20Incremental%20Runtime%20Repository%20Data%20Service/Import"
									def jsonBody = """
									{
										 "body":
										 { 
										 "filename": "$repository_id", 
										 "migrationid": "$migrationid"
										}
										}
									"""

									def response = sh(
										script: """
											curl -s -X POST '${apiUrl}' \\
												 -u "$USER:$PASS" \\
												 -H 'Content-Type: application/json' \\
												 -d '${jsonBody}'
										""",
										returnStdout: true
									).trim()
									def json = readJSON text: response
									repository_trackingid=json.trackingid
									echo "Response:${json}"
							}
						}
					else{
					  echo "Repository Import is not applicable"
                    }					
			  }
            }
        }
		stage('Repository Import Get Status'){
            steps {
			   script{
			   if(repository_id){
                withCredentials([usernamePassword(credentialsId: "${env.Environment}_SADMIN", usernameVariable: 'USER', passwordVariable: 'PASS')]) {
						while(true){
								def apiUrl = "https://${Host_Name}:9112/siebel/v1.0/service/Migration%20Incremental%20Runtime%20Repository%20Data%20Service/GetStatus"
								def jsonBody = """
								{
									 "body":
									 { 
									 "migrationid": "$migrationid",
									 "trackingid": "$repository_trackingid",
									 "getlog": "true"
									}
									}
								"""

								def response = sh(
									script: """
										curl -s -X POST '${apiUrl}' \\
											 -u "$USER:$PASS" \\
											 -H 'Content-Type: application/json' \\
											 -d '${jsonBody}'
									""",
									returnStdout: true
								).trim()
								def json = readJSON text: response
								status=json.status
								echo "$json"
								
							    if(status!="running")
								{
									echo"Export completed with status:${status}"
									break;
								}
								sleep time: 300, unit: 'SECONDS'
					  }	   
                    }
				  }
                }
            }
        }
		stage('Schema Import') {
            steps {
			  script {
			  if(schema_id){
                withCredentials([usernamePassword(credentialsId: "${env.Environment}_SADMIN", usernameVariable: 'USER', passwordVariable: 'PASS'),usernamePassword(credentialsId: "${env.Environment}_SIEBEL", usernameVariable: 'USER_SIEBEL', passwordVariable: 'PASS_SIEBEL')]) 
				{
					    def Password="${PASS_SIEBEL}"
					    def schemaPassword=Password.bytes.encodeBase64().toString()                        
                        def apiUrl = "https://${Host_Name}:9112/siebel/v1.0/service/Migration%20Schema%20Service/Import"
                        def jsonBody = """
						{
							 "body":
							 { 
							 "filename": "$schema_id", 
							 "migrationid": "$migrationid",
							 "username": "SIEBEL",
							 "password":"$schemaPassword"
							 
							}
							}
						"""

                        def response = sh(
                            script: """
                                curl -s -X POST '${apiUrl}' \\
                                     -u "$USER:$PASS" \\
                                     -H 'Content-Type: application/json' \\
                                     -d '${jsonBody}'
                            """,
                            returnStdout: true
                        ).trim()
                       	def json = readJSON text: response
						schema_trackingid=json.trackingid
                        echo "Response:${json}"
                        
                    }
                }
			 else{
			       echo "Schema Import is not applicable"
			 }
		    } 
          }
        }
        stage('Schema Import Status')
        {
            steps {
			  script {
			   if(schema_id){
                withCredentials([usernamePassword(credentialsId: "${env.Environment}_SADMIN", usernameVariable: 'USER', passwordVariable: 'PASS')]) {
						while(true){
								def apiUrl = "https://${Host_Name}:9112/siebel/v1.0/service/Migration%20Schema%20Service/GetStatus"
								def jsonBody = """
								{
									 "body":
									 { 
									 "migrationid": "$migrationid",
									 "trackingid": "$schema_trackingid",
									 "getlog": "true"
									}
									}
								"""

								def response = sh(
									script: """
										curl -s -X POST '${apiUrl}' \\
											 -u "$USER:$PASS" \\
											 -H 'Content-Type: application/json' \\
											 -d '${jsonBody}'
									""",
									returnStdout: true
								).trim()
								def json = readJSON text: response
								status=json.status
								echo "$json"
								
							    if(status!="running")
								{
									echo"Export completed with status:${status}"
									break;
								}
								sleep time: 60, unit: 'SECONDS'
					  }	   
                    }
                }
			   }	
            }
        }
		  stage('Application Workspace Data Service Import') {
            steps {
			  script {
			   if(seed_id){
                withCredentials([usernamePassword(credentialsId: "${env.Environment}_SADMIN", usernameVariable: 'USER', passwordVariable: 'PASS')]) 
				{
                        def apiUrl = "https://${Host_Name}:9112/siebel/v1.0/service/Migration%20Incremental%20Application%20Workspace%20Data%20Service/Import"
                        def jsonBody = """
						{
							 "body":
							 { 
							 "filename": "$seed_id", 
							 "migrationid": "$migrationid"
							}
							}
						"""

                        def response = sh(
                            script: """
                                curl -s -X POST '${apiUrl}' \\
                                     -u "$USER:$PASS" \\
                                     -H 'Content-Type: application/json' \\
                                     -d '${jsonBody}'
                            """,
                            returnStdout: true
                        ).trim()
                       	def json = readJSON text: response
						seed_trackingid=json.trackingid
                        echo "Response:${json}"
                        
                    }
                }
				else{
				 echo "Application LOV Import is not applicable"
				}
			  }
            }
        }
        stage('Application Workspace Data Service Status')
        {
            steps {
			  script {
			   if(seed_id){
                withCredentials([usernamePassword(credentialsId: "${env.Environment}_SADMIN", usernameVariable: 'USER', passwordVariable: 'PASS')]) {
						while(true){
								def apiUrl = "https://${Host_Name}:9112/siebel/v1.0/service/Migration%20Incremental%20Application%20Workspace%20Data%20Service/GetStatus"
								def jsonBody = """
								{
									 "body":
									 { 
									 "migrationid": "$migrationid",
									 "trackingid": "$seed_trackingid",
									 "getlog": "true"
									}
									}
								"""

								def response = sh(
									script: """
										curl -s -X POST '${apiUrl}' \\
											 -u "$USER:$PASS" \\
											 -H 'Content-Type: application/json' \\
											 -d '${jsonBody}'
									""",
									returnStdout: true
								).trim()
								def json = readJSON text: response
								status=json.status
								echo "$json"
								
							    if(status!="running")
								{
									echo"Export completed with status:${status}"
									break;
								}
								sleep time: 60, unit: 'SECONDS'
					  }	   
                    }
                }
			  }
            }
        }
    }
}