pipeline {
    agent {
	 	node{
			label 'built-in'
			customWorkspace '/tmp/siebel_import'
	 	}
	}
    environment {
       	//def Ansible_Host_Name = "app_server_01"
	   	def Repo_Name = "bpm"
		def error_message = ""
	   	def History_ID = ""
    }
    stages {
		stage('Checkout devops automation repository') {
			steps{			
				checkout scm			
			}
	    }
		stage('Environment Name') {
		  	steps {
				echo "Variables: ${env.Environment},${env.Branch_Name},${env.Mig_Plan_Name},${env.packageFilename},${env.packageFilename}"
			}
		}
		
        stage('Git pull and place to sfs folder') {
            steps{
                withCredentials([string(credentialsId: 'github_access_token_secret', variable: 'GITHUB_TOKEN')]) { 
                    ansiColor('xterm') {
                        ansiblePlaybook(
                            playbook: "${WORKSPACE}/Siebel_Migration_Import_IRR/ansible_scripts/package_copy.yml",
                            inventory: "${WORKSPACE}/Siebel_Migration_Import_IRR/ansible_scripts/Inventory/siebel_env.yml",
                            colorized: true,
                            extraVars: [
                                env: "${env.Environment}",
                                repo_name: "bpm",
								packageFilename: "${env.packageFilename}",
                                git_token: "${GITHUB_TOKEN}",
                                Branch_Name: "${Branch_Name}"
                            ]
                        )
                    }
                }
            }	
        }

/* 
		stage('Git Clone of Siebel repository') {
			steps {
				script {
					withCredentials([string(credentialsId: 'github_access_token_secret', variable: 'BITBUCKET_TOKEN')]) {
						//sh("git clone https://x-token-auth:${BITBUCKET_TOKEN}@${GIT_FQDN}/dhs-kolea/sbl_code_repo.git --branch ${env.Branch_Name}")
						def response = sh(
							script: """
								rm -rf ${Repo_Name}						 
								git clone --filter=blob:none --sparse https://x-token-auth:${BITBUCKET_TOKEN}@github.com/cheolminhwang/${Repo_Name}.git --branch ${env.Branch_Name}
								cd ${Repo_Name}
								git sparse-checkout set DeploymentArtifacts                   
							""",
							returnStdout: true
						).trim() 
						echo "response:${response}"               
					}
				}
			}
	  	}
		stage('Running Ansible to copy export zipfile') {
		 steps{
			ansiColor('xterm') {
				ansiblePlaybook(
					playbook: "${WORKSPACE}/Siebel_Migration_Import_IRR/ansible_scripts/package_copy.yml",
					inventory: "${WORKSPACE}/Siebel_Migration_Import_IRR/ansible_scripts/Inventory/siebel_env.yml",
					colorized: true,
					extraVars: [
						env: "${env.Environment}",
						Branch_Name: "${env.Branch_Name}",
						Repo_Name: "${Repo_Name}",
						packageFilename: "${env.packageFilename}",
						workspace: "${WORKSPACE}"
					]
				)
			}
		  }	
		} */
		stage('===============Repository Import with migration plan') {
            steps {
			    script{				
					withCredentials([usernamePassword(credentialsId: "${env.Environment}_SADMIN", usernameVariable: 'USER', passwordVariable: 'PASS')]) {
						def apiUrl = "https://${Host_Name}:4430/siebel/v1.0/migration/execution/${env.Mig_Plan_Name}"
						def jsonBody = """
							{
								"schemaPassword": "OPKNuIA/pwISiUu2zjy9/wXjFQAA",
								"pwdPreEncrypted":"true",
								"packageFilename": "${env.packageFilename}"
							}
							"""
							// schemaPassword  <== siebsrvr/bin/encryptstring SIEBEL_PASSWORD

						def response = sh(
							script: """
								curl -s --location --insecure --request POST '${apiUrl}' \\
										-u "$USER:$PASS" \\
										-H 'Content-Type: application/json' \\
										-d '${jsonBody}'
							""",
							returnStdout: true
						).trim()
						try {
							if (response) {
								//echo "Migration API Response: ${response}"
								def json = readJSON text: response
								error_message=json.error
								status=json.status
								History_ID=json.id
									echo "Schema Export Response ${History_ID}: err:${error_message},  Status:${status}"
							} else {
								echo "No response received from migration API."
								error "No response received from migration API."
							}
						} catch (Exception e) {
							echo "Failed to parse migration response: ${e.message}"
							error "Failed to parse migration response: ${e.message}"
						}	
					}									
			  	}
            }
        }
		stage('===============Repository Import Get Status'){
            steps {
			   	script{
			   		if(History_ID){
                		withCredentials([usernamePassword(credentialsId: "${env.Environment}_SADMIN", usernameVariable: 'USER', passwordVariable: 'PASS')]) {
							while(true){
								def apiUrl = "https://${Host_Name}:4430/siebel/v1.0/migration/execution/${env.Mig_Plan_Name}"
								def jsonBody = """
								{ }
								"""

								def response = sh(
									script: """
										curl -s --location --insecure --request GET '${apiUrl}' \\
											 -u "$USER:$PASS" \\
											 -H 'Content-Type: application/json' \\
											 -d '${jsonBody}'
									""",
									returnStdout: true
								).trim()
								try {
									if (response) {
										//echo "Migration API Response: ${response}"
										def json = readJSON text: response
										error_message=json.error
										status=json.status
										
										echo "Schema Export Response ${History_ID}: err:${error_message},  Status:${status}"
									} else {
										echo "No response received from migration API."
										error "No response received from migration API."
									}
									
								} catch (Exception e) {
									echo "Failed to parse migration response: ${e.message}"
									//error "Failed to parse migration response: ${e.message}"
								}	
								
							if(status == null || !status.equalsIgnoreCase("running"))
								{
									echo"Export completed with status:${status}"
									break;
								}
								sleep time: 120, unit: 'SECONDS'
					  		}	   
                    	}
				  	}
                }
            }
        }
		stage('===============Repository Import Status at History'){
            steps {
			   	script{
			   		if(History_ID){
                		withCredentials([usernamePassword(credentialsId: "${env.Environment}_SADMIN", usernameVariable: 'USER', passwordVariable: 'PASS')]) {
						
							def apiUrl = "https://${Host_Name}:4430/siebel/v1.0/migration/history/${History_ID}"
							def jsonBody = """
								{ }
								"""

							def response = sh(
								script: """
									curl -s --location --insecure --request GET '${apiUrl}' \\
										 -u "$USER:$PASS" \\
										 -H 'Content-Type: application/json' \\
										 -d '${jsonBody}'
								""",
								returnStdout: true
							).trim()
							try {
								if (response) {
									echo "Migration API Response: ${response}"
									def json = readJSON text: response
									error_message=json.error
									status=json.status
									 
									echo "Schema Export Response ${History_ID}: err:${error_message},  Status:${status}"
								} else {
									echo "No response received from migration API."
									error "No response received from migration API."
								}
								
							} catch (Exception e) {
								echo "Failed to parse migration response: ${e.message}"
								//error "Failed to parse migration response: ${e.message}"
							}						
							
							echo"Export completed with status:${status}"
                    	}
				  	}	
                }
            }
        }
		stage('=================================Initiate Watermark job after import') {
			when {
				expression { return status != "NOGOOD" }
			}
            steps {
                build job: 'Siebel_Migration_Watermark_Generation',  
                      wait: true,             // Wait for completion (default)
                      propagate: true,        // Propagate failure back to this pipeline (default)
                      parameters: [
                          string(name: 'Environment', value: "${env.Environment}"), 
                          string(name: 'Host_Name', value: "${env.Host_Name}"), 
                          string(name: 'File_Name', value: "watermark.txt") //${env.Environment}_watermark.txt
                      ]
            }
        }

    }
}