
pipeline {
    agent {
	    node{
			label 'built-in'
			//customWorkspace '/stage/asi/automations/Siebel_Migration_Redeploy'
            customWorkspace '/tmp/Siebel_Migration_Redeploy'
     	}  
	}
    environment {
        def error_message = ""
        //def fqdn = "${URL_MQD}/kolea/CRM"
        def sbl_repo = "sbl_code_repo"
        def MIG_NAME = "Mig_Prof"
        def MIG_DESC = "Migration Desc"
    }
    stages {
		stage('Checkout devops automation repository') {
			steps{			
				checkout scm			
			}
	    } 

		stage('=================================Environment ') {
		  steps {
			echo "Variables: ${env.Environment} ${env.Host_Name} ${env.Host_Port} ${env.Profile_Name} "
			}
		}
		stage('=================================Target Environment  ') {
            steps {
                withCredentials([usernamePassword(credentialsId: "${env.Environment}_SADMIN", usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    script {
                        def response = sh(
                            script: """
                                bash ${WORKSPACE}/deleteMigration.sh -u ${USER} -p ${PASS} -a ${env.Host_Name} -b ${env.Host_Port} -d ${env.Profile_Name}
                            """,
                            returnStdout: true
                        ).trim()
                        echo "response: ${response}" 
                        def response2 = sh(
                            script: """"
                                bash ${WORKSPACE}/deployMigration.sh -u ${USER} -p ${PASS} -a ${env.Host_Name} -b ${env.Host_Port} -d ${env.Profile_Name} -e ${MIG_NAME} -f ${MIG_DESC} "
                            """,
                            returnStdout: true
                        ).trim()
                        echo "response2: ${response2}" 
                    }
                }
            }
        }
    }
}