pipeline {
    agent {
	 	node{
			label 'built-in'
			customWorkspace '/tmp/siebel_export'
	 	}
	}
    environment {
	   	def status = ""
	   	def History_ID = ""
	   	def trackingid = ""
	   	//def Repository_Name="${env.Repository_Name}"
	   	def fqdn="github.com/cheolminhwang"
    }
    stages {
		stage('Cleanup') {
            steps {
                cleanWs()  // Deletes workspace contents
            }
        }
		stage('Checkout') {
			steps {
				checkout scm
			}			
        }
		stage('Environment Name') {
		  steps {
			echo "Env_Variable: ${env.Environment}"
			//echo "RepoName_Variable: ${env.Repository_Name}"
			echo "WaterMark_Variable:${env.watermark}"
			echo "packageFilename:${env.packageFilename}"
			echo "Branch_Name: ${env.Branch_Name}"
			}
		}
        stage('Git pull and place to sfs folder') {
            steps{
                withCredentials([string(credentialsId: 'github_access_token_secret', variable: 'GITHUB_TOKEN')]) { 
                    ansiColor('xterm') {
                        ansiblePlaybook(
                            playbook: "${WORKSPACE}/Siebel_Migration_Export_Inc/ansible_scripts/watermark_copy.yml",
                            inventory: "${WORKSPACE}/Siebel_Migration_Export_Inc/ansible_scripts/Inventory/siebel_env.yml",
                            //credentialsId: 'jenkins_private_key',
                            colorized: true,
                            extraVars: [
                                env: "${env.Environment}",
                                repo_name: "bpm",
                                watermark: "${env.watermark}",
                                git_token: "${GITHUB_TOKEN}",
                                Branch_Name: "${Branch_Name}"
                            ]
                        )
                    }
                }
            }	
        }
		/* 		
		stage('Git Clone of Watermark file') {
			steps {
				script {
					withCredentials([string(credentialsId: 'github_access_token_secret', variable: 'BITBUCKET_TOKEN')]) {
						def response = sh(
							script: """
								rm -rf ${Repository_Name}						 
								git clone --filter=blob:none --sparse https://x-token-auth:${BITBUCKET_TOKEN}@${fqdn}/${Repository_Name}.git --branch ${env.Branch_Name}
								cd ${Repository_Name}
								git sparse-checkout set DeploymentArtifacts                   
							""",
							returnStdout: true
						).trim() 
						echo "response:${response}"               
					}
				}
			}
	  	} */

        stage('Schema Export') {
            steps {
			   	script {
                	withCredentials([usernamePassword(credentialsId: "${env.Environment}_SADMIN", usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    
                        def apiUrl = "https://${Host_Name}:4430/siebel/v1.0/migration/execution/${env.Mig_Plan_Name}"
                        def jsonBody = """
						{
    						"packageFilename": "${env.Environment}_${env.packageFilename}",
    						"watermarkFilename": "${env.watermark}"							
						}
						"""

                        def response = sh(
                            script: """
                                curl --location --insecure --request POST '${apiUrl}' \\
                                     -u "$USER:$PASS" \\
                                     -H 'Content-Type: application/json' \\
                                     -d '${jsonBody}'  2>&1
                            """,
                            returnStdout: true
                        ).trim()
						try {
							if (response) {
								echo "Migration API Response: ${response}"
								def json = readJSON text: response
								trackingid=json.trackingid
								status=json.status
								History_ID=json.id
								echo "Schema Export Response ${History_ID}: tracking Id:${trackingid}, Status:${status}"
							} else {
								echo "No response received from migration API."
								error "No response received from migration API."
							}
							 
						} catch (Exception e) {
							echo "Failed to parse migration response: ${e.message}"
							error "Failed to parse migration response: ${e.message}"
						}	
                    }              		  
			  	}	
            }
        }
        stage('Schema Export Status') {
            steps {
			   	script {
                	withCredentials([usernamePassword(credentialsId: "${env.Environment}_SADMIN", usernameVariable: 'USER', passwordVariable: 'PASS')]) {
						while(true){
							def apiUrl = "https://${Host_Name}:4430/siebel/v1.0/migration/execution/${env.Mig_Plan_Name}"
							def jsonBody = """
							{		
							}
							"""

							def response = sh(
								script: """
									curl -s -X GET '${apiUrl}' \\
										-u "$USER:$PASS" \\
										-H 'Content-Type: application/json' \\
										-d '${jsonBody}'
								""",
								returnStdout: true
							).trim()
							def json = readJSON text: response
							trackingid=json.trackingid
							status=json.status
							History_ID=json.id
							echo "Schema Export Response ${History_ID}: tracking Id:${trackingid}, Status:${status}"
														    
							if(!status.equalsIgnoreCase("running"))
								{
									echo"Export completed with status:${status}"
									break;
								}
								sleep time: 300, unit: 'SECONDS'
						}
                    }             		  
			  	}	
            }
        }
		stage('Repository Import Status at History'){
            steps {
			   	script{
			   		if(History_ID){
                		withCredentials([usernamePassword(credentialsId: "${env.Environment}_SADMIN", usernameVariable: 'USER', passwordVariable: 'PASS')]) {
						
							def apiUrl = "https://${Host_Name}:4430/siebel/v1.0/migration/history/${History_ID}"
							def jsonBody = """
								{ }
								"""

							def response = sh(
								script: """
									curl -s -X GET '${apiUrl}' \\
										 -u "$USER:$PASS" \\
										 -H 'Content-Type: application/json' \\
										 -d '${jsonBody}'
								""",
								returnStdout: true
							).trim()
							def json = readJSON text: response
							status=json.status
							echo "$json"
								
							
									echo"Export completed with status:${status}"
									 
												  	   
                    	}
				  	}	
                }
            }
        }
        stage('Git push') {
            steps{
                withCredentials([string(credentialsId: 'github_access_token_secret', variable: 'GITHUB_TOKEN')]) { 
                    ansiColor('xterm') {
                        ansiblePlaybook(
                            playbook: "${WORKSPACE}/Siebel_Migration_Export_Inc/ansible_scripts/package_copy.yml",
                            inventory: "${WORKSPACE}/Siebel_Migration_Export_Inc/ansible_scripts/Inventory/siebel_env.yml",
                            //credentialsId: 'jenkins_private_key',
                            colorized: true,
                            extraVars: [
                                env: "${env.Environment}",
                                repo_name: "bpm",
                                packageFilename: "${env.Environment}_${env.packageFilename}",
                                git_token: "${GITHUB_TOKEN}",
                                Branch_Name: "${Branch_Name}"
                            ]
                        )
                    }
                }
            }	
        }
   }
}
