all:
  hosts:
    osai:
      ansible_host: oses
      ansible_port: 2220
      ansible_connection: ssh  

    PSD11:
      ansible_host: psd11vsbl01.dhsie.hawaii.gov
      ansible_connection: ssh  

