---
- hosts: "{{ env }}"
  gather_facts: no
  remote_user: devopsadmin
  become: yes
  become_user: siebel
  become_method: sudo
  
  vars_files:
    - ../../ansible_automation_password_vault.yml
  
  vars:
    backup_date: "{{ '%m%d%Y' | strftime }}"
    tmp_folder: "/tmp"
    sfs_folder: "/sfs/migration" 
    
  tasks:
    
    - name: Print environment and branch name
      debug:
        msg: "Running playbook in Environment: {{ env }}, repo_name: {{ repo_name }}, Branch_Name: {{ Branch_Name }}, watermark: {{ watermark }}"
      run_once: true  

    - name: Check if target tmp dir exists
      stat:
        path: "{{ tmp_folder }}/migration"
      register: export_tmp_dir
      run_once: true


    - name: Removing existing tmp dir
      shell: |
        cd {{ tmp_folder }}
        rm -rf migration
        mkdir migration
      ##when: export_tmp_dir.stat.isdir is defined and export_tmp_dir.stat.isdir
      run_once: true

    - name: Clone
      ansible.builtin.shell: |
        cd {{ tmp_folder }}/migration
        git clone --filter=blob:none --sparse https://x-token-auth:{{ git_token }}@github.com/cheolminhwang/{{ repo_name }}.git --branch {{ Branch_Name }}
        cd {{ repo_name }}
        git sparse-checkout set DeploymentArtifacts
      #args:
      #  chdir: "{{ tmp_folder }}/migration"

    - name: Copy Export Folder from Siebel repository to siebel sfs folder
      copy:
        src: "{{ tmp_folder }}/migration/{{ repo_name }}/DeploymentArtifacts/{{ watermark }}"
        dest: "{{ sfs_folder }}"
        force: yes
        mode: '0777'
        remote_src: true

        