pipeline {
    agent {
		node{
			label 'built-in'
			customWorkspace '/tmp/Jenkins_Sec_Update'
		}
	}
    environment {       
	   	def url = ""

    }
    stages {		 
		stage('Cleanup') {
			steps {				
                deleteDir()
			}
		}
		
		stage('Checkout') {
			steps {
				checkout scm
			}			
		}
        stage('Environment Name') {
		  steps {
			echo "Env_Variable: ${env.Environment}"
			//echo "RepoName_Variable: ${env.Repository_Name}"
			 
			}
		}		
        stage('Execution') {
            steps {
                script {
                    // Determine the URL based on the environment
                    def jenkinsUrl = ""
                    switch (env.Environment) {
                        case 'prod':    jenkinsUrl = "https://build.dhsie.hawaii.gov"; break
                        case 'nonprod': jenkinsUrl = "http://localhost"; break
                        default:        jenkinsUrl = "https://build-oci.dhsie.hawaii.gov"; break
                    }

                    sh """
                        cd Jenkins_Sec_Update
                        wget ${jenkinsUrl}/jnlpJars/jenkins-cli.jar
                        wget https://github.com/jenkinsci/plugin-installation-manager-tool/releases/download/2.13.2/jenkins-plugin-manager-2.13.2.jar
                        python3 pyUpdatePlugins.py
                    """
                }
            }
        }ß

        stage('SafeRestart') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'jenkins-username-password', usernameVariable: 'J_USER', passwordVariable: 'J_PASS')]) {
                        def response = sh(
                            script: """
                                cd Jenkins_Sec_Update
                                switch ("${env.Environment}") {
                                    case 'prod':
                                        bash ./shSafeRestart.sh https://build.dhsie.hawaii.gov  jenkins $J_PASS
                                        break 
                                    case 'nonprod': 
                                        bash ./shSafeRestart.sh http://localhost  jenkins $J_PASS
                                        break
                                    default:
                                        bash ./shSafeRestart.sh https://build-oci.dhsie.hawaii.gov  jenkins $J_PASS
                                    break
                                }       
                            """,
                            returnStdout: true
                        ).trim() 
                        echo "response:${response}"               
                    }
                }
            }
        }   
    }
}