#!/usr/bin/env groovy

/*
** Jenkins Pipeline for Siebel Repository Rename
*/

node {
    ws('/tmp/siebel_repository_rename') {
        timestamps {
            stage('Cleanup Workspace') {
                // Cleanup Workspace
                deleteDir()
            }

            stage('Checkout Automation Scripts') {
                // Checkout pipeline code base from Git
                checkout scm
            }

            stage('Playbook Run') {
                withCredentials([usernamePassword(credentialsId: "${env.Environment}_SIEBEL", usernameVariable: 'USER_SIEBEL', passwordVariable: 'PASS_SIEBEL')]){
                ansiColor('xterm') {
                    ansiblePlaybook(
                        playbook: "${workspace}/Siebel/Siebel_Repository_Rename/ansible_scripts/siebelrepositoryrename.yml",
                        inventory: "${workspace}/Siebel/Siebel_Repository_Rename/ansible_scripts/inventory/${env.Environment}/${env.Environment}.yml",
                        colorized: true,
                        extraVars: [
                            Env: "${env.Environment}",
							siebel_password: "${PASS_SIEBEL}",
							tns_servicename: "${env.TNS_Identifier}"
                        ]						
                    )
                }
            }
		  }
        }
    }
}